version: '2'
services:
    backend:
        build:
            context: ./backend_app
        container_name: "backend"
        volumes:
            - ./backend_app:/code
        ports:
            - 5000:5000
        command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    frontend:
        build:
            context: ./frontend_app
        container_name: "frontend"
        links:
            - "backend:backend_app"
        volumes:
            - ./frontend_app:/code
        ports:
            - 8000:8000
        depends_on:
          - backend
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
